# Generated by Django 2.1.1 on 2018-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_created', models.DateTimeField(verbose_name='Created')),
                ('task_due_on', models.DateTimeField(verbose_name='Due on')),
                ('task_owner', models.CharField(max_length=200)),
            ],
        ),
    ]
