# Generated by Django 2.1.1 on 2018-09-14 12:37

from django.db import migrations, models
import getpass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_done',
            field=models.NullBooleanField(verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_owner',
            field=models.CharField(max_length=200, verbose_name=getpass.getuser),
        ),
    ]
