# Generated by Django 2.1.1 on 2018-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180914_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_owner',
            field=models.CharField(max_length=200, verbose_name='getuser'),
        ),
    ]
